name: Deploy to Stg
on:
  workflow_run:
    workflows: [Test and Build]
    types:
      - completed 
  workflow_dispatch:

jobs:
  deploy-stg:
    name: deploy-stg
    environment: stg
    runs-on: ubuntu-20.04
    steps:
      - name: Command
        run: |-
          echo ${{github.event.workflow_run}}
          echo $GITHUB_SHA