name: Deploy to Stg
on:
  workflow_run:
    workflows: [Test and Build]
    types:
      - completed 
  workflow_dispatch:

jobs:
  deploy-stg:
    name: deploy-stg
    environment: stg
    runs-on: ubuntu-20.04
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)