name: Deploy to Prd
on:
  workflow_run:
    workflows: [Deploy to Stg]
    types:
      - completed 
jobs:
  deploy-prd:
    name: deploy-prd
    # environment: prd
    runs-on: ubuntu-20.04
    steps:
      - name: Command
        run: |-
          echo ${{github.event.workflow_run}}
          echo $GITHUB_SHA