name: Test and Build
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Command
        run: |-
          env
  build:
    name: build
    runs-on: ubuntu-20.04
    needs:
      - test
    steps:
      - name: Command
        run: |-
          env
  deploy-test:
    name: deploy-test
    environment: test
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - name: Command
        run: |-
          env
